/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VideosImport } from './routes/videos'
import { Route as RecordImport } from './routes/record'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as VideosIdImport } from './routes/videos_.$id'

// Create/Update Routes

const VideosRoute = VideosImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRoute,
} as any)

const RecordRoute = RecordImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VideosIdRoute = VideosIdImport.update({
  id: '/videos_/$id',
  path: '/videos/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordImport
      parentRoute: typeof rootRoute
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosImport
      parentRoute: typeof rootRoute
    }
    '/videos_/$id': {
      id: '/videos_/$id'
      path: '/videos/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof VideosIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/record': typeof RecordRoute
  '/videos': typeof VideosRoute
  '/videos/$id': typeof VideosIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/record': typeof RecordRoute
  '/videos': typeof VideosRoute
  '/videos/$id': typeof VideosIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/record': typeof RecordRoute
  '/videos': typeof VideosRoute
  '/videos_/$id': typeof VideosIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/record' | '/videos' | '/videos/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/record' | '/videos' | '/videos/$id'
  id: '__root__' | '/' | '/admin' | '/record' | '/videos' | '/videos_/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  RecordRoute: typeof RecordRoute
  VideosRoute: typeof VideosRoute
  VideosIdRoute: typeof VideosIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  RecordRoute: RecordRoute,
  VideosRoute: VideosRoute,
  VideosIdRoute: VideosIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/record",
        "/videos",
        "/videos_/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx"
    },
    "/record": {
      "filePath": "record.tsx"
    },
    "/videos": {
      "filePath": "videos.tsx"
    },
    "/videos_/$id": {
      "filePath": "videos_.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
